# Daytona Configuration for Nurdscode
# Alternative container runtime configuration

name: nurdscode-app
version: 1.0.0

# Container configuration
container:
  image: node:20-alpine
  workdir: /workspace

# Build configuration
build:
  commands:
    - npm ci
    - npm run build
  
# Development server
dev:
  command: npm run dev
  port: 3000
  env:
    NODE_ENV: development

# Production server  
prod:
  command: nginx -g "daemon off;"
  port: 80
  env:
    NODE_ENV: production

# Environment variables
env:
  VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
  VITE_API_URL: ${VITE_API_URL}

# Ports to expose
ports:
  - 3000  # Development
  - 80    # Production (nginx)
  - 8787  # Workers (if running locally)

# Volume mounts
volumes:
  - src:/workspace/src
  - dist:/workspace/dist

# Health check
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost/"]
  interval: 30s
  timeout: 3s
  retries: 3
  start_period: 5s
