import { useState, useEffect } from 'react';
import { c1Service } from '../services/c1-thesys-service';

/**
 * C1 Card Component
 * Renders interactive cards generated by C1 Thesys
 */
export function C1Card({ prompt, data, type, className = '' }) {
  const [card, setCard] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadCard() {
      try {
        setLoading(true);
        const result = await c1Service.generateCard(prompt, data, type);
        setCard(result);
      } catch (err) {
        console.error('Failed to load C1 card:', err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    loadCard();
  }, [prompt, data, type]);

  if (loading) {
    return (
      <div className={`c1-card-loading ${className}`}>
        <div className="animate-pulse bg-linear-to-r from-[#E68961] to-[#D4A05F] h-48 rounded-lg" />
      </div>
    );
  }

  if (error) {
    return (
      <div className={`c1-card-error ${className} bg-red-950 border border-red-500 rounded-lg p-6`}>
        <h3 className="text-red-400 font-bold mb-2">Card Error</h3>
        <p className="text-red-300 text-sm">{error}</p>
      </div>
    );
  }

  if (!card) {
    return null;
  }

  return (
    <div 
      className={`c1-card ${className}`}
      dangerouslySetInnerHTML={{ __html: card.html }}
    />
  );
}

/**
 * Specialized C1 Card Components
 */

export function C1AgentCard({ agent, className }) {
  return (
    <C1Card
      type="agent-performance"
      data={agent}
      prompt={`Display agent: ${agent.name}`}
      className={className}
    />
  );
}

export function C1BuildCard({ build, className }) {
  return (
    <C1Card
      type="build-output"
      data={build}
      prompt={`Display build results`}
      className={className}
    />
  );
}

export function C1TokenDashboard({ tokens, className }) {
  return (
    <C1Card
      type="token-dashboard"
      data={tokens}
      prompt={`Display token usage dashboard`}
      className={className}
    />
  );
}

export function C1PricingCard({ tier, className }) {
  return (
    <C1Card
      type="pricing"
      data={tier}
      prompt={`Display pricing tier: ${tier.name}`}
      className={className}
    />
  );
}

export function C1AnalyticsCard({ analytics, className }) {
  return (
    <C1Card
      type="chart"
      data={analytics}
      prompt={`Display analytics: ${analytics.metric}`}
      className={className}
    />
  );
}

export function C1TableCard({ table, className }) {
  return (
    <C1Card
      type="table"
      data={table}
      prompt={`Display table: ${table.title}`}
      className={className}
    />
  );
}

export function C1ProgressCard({ progress, className }) {
  return (
    <C1Card
      type="progress"
      data={progress}
      prompt={`Display progress: ${progress.task}`}
      className={className}
    />
  );
}

export function C1AlertCard({ alert, className }) {
  return (
    <C1Card
      type="alert"
      data={alert}
      prompt={`Display ${alert.type} alert`}
      className={className}
    />
  );
}

/**
 * C1 Card Grid - Display multiple cards in responsive grid
 */
export function C1CardGrid({ cards, columns = 3, className = '' }) {
  const gridCols = {
    1: 'grid-cols-1',
    2: 'grid-cols-1 md:grid-cols-2',
    3: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
    4: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-4',
  };

  return (
    <div className={`grid ${gridCols[columns]} gap-6 ${className}`}>
      {cards.map((card, index) => (
        <C1Card
          key={index}
          prompt={card.prompt}
          data={card.data}
          type={card.type}
        />
      ))}
    </div>
  );
}

export default C1Card;
