/**
 * II-Agent Worker - Express Handler Template
 * Cloud Run compatible service
 */

import express, { Request, Response } from 'express';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 8080;
const AGENT_TYPE = process.env.AGENT_TYPE || 'generic';

// Middleware
app.use(cors());
app.use(express.json());

// Health check endpoint (required for Cloud Run)
app.get('/health', (req: Request, res: Response) => {
  res.json({
    status: 'healthy',
    agent: AGENT_TYPE,
    timestamp: new Date().toISOString(),
  });
});

// Main processing endpoint
app.post('/process', async (req: Request, res: Response) => {
  try {
    const { prompt, flags, context } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    console.log(`[${AGENT_TYPE}] Processing: "${prompt.substring(0, 50)}..."`);

    // Agent-specific processing logic
    const result = await processAgentTask(prompt, flags, context);

    res.json({
      agent: AGENT_TYPE,
      output: result,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error(`[${AGENT_TYPE}] Error:`, error);
    res.status(500).json({
      error: error instanceof Error ? error.message : 'Processing failed',
      agent: AGENT_TYPE,
    });
  }
});

// Code generation endpoint (for ii-codegen-worker)
app.post('/generate', async (req: Request, res: Response) => {
  try {
    const { description, language = 'javascript' } = req.body;

    if (!description) {
      return res.status(400).json({ error: 'Description is required' });
    }

    console.log(`[${AGENT_TYPE}] Generating ${language} code...`);

    // Use Groq for fast code generation
    const code = await generateCode(description, language);

    res.json({
      code,
      language,
      status: 'generated',
      agent: AGENT_TYPE,
    });
  } catch (error) {
    console.error(`[${AGENT_TYPE}] Generation error:`, error);
    res.status(500).json({
      error: error instanceof Error ? error.message : 'Generation failed',
    });
  }
});

// ============================================
// AGENT-SPECIFIC LOGIC (Customize per agent)
// ============================================

async function processAgentTask(
  prompt: string,
  flags: Record<string, boolean> = {},
  context: any[] = []
): Promise<string> {
  // Agent-specific processing
  switch (AGENT_TYPE) {
    case 'nlu':
      return classifyIntent(prompt);
    case 'codegen':
      return await generateCode(prompt, 'javascript');
    case 'research':
      return await performResearch(prompt);
    case 'validation':
      return validateCode(prompt);
    case 'security':
      return securityScan(prompt);
    default:
      return `[${AGENT_TYPE}] Processed: ${prompt}`;
  }
}

function classifyIntent(text: string): string {
  const lower = text.toLowerCase();
  if (lower.includes('code') || lower.includes('generate')) return 'code_generation';
  if (lower.includes('analyze') || lower.includes('review')) return 'analysis';
  if (lower.includes('search') || lower.includes('find')) return 'research';
  return 'general';
}

async function generateCode(description: string, language: string): Promise<string> {
  const GROQ_API_KEY = process.env.GROQ_API_KEY;
  
  if (!GROQ_API_KEY) {
    return `// Generated by II-Codegen (no API key)\n// ${description}\nconsole.log("Hello, World!");`;
  }

  try {
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GROQ_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama3-70b-8192',
        messages: [
          {
            role: 'system',
            content: `You are an expert ${language} developer. Generate clean, production-ready code. Only output code, no explanations.`,
          },
          {
            role: 'user',
            content: description,
          },
        ],
        temperature: 0.3,
        max_tokens: 2000,
      }),
    });

    const data = await response.json() as any;
    return data.choices?.[0]?.message?.content || `// Error generating code`;
  } catch (error) {
    console.error('Groq API error:', error);
    return `// Generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`;
  }
}

async function performResearch(query: string): Promise<string> {
  return `Research results for: "${query}"\n- Finding 1: ...\n- Finding 2: ...`;
}

function validateCode(code: string): string {
  return `Validation passed. No critical issues found.`;
}

function securityScan(code: string): string {
  return `Security scan complete. 0 vulnerabilities detected.`;
}

// Start server
app.listen(PORT, () => {
  console.log(`[${AGENT_TYPE}] Worker running on port ${PORT}`);
});
